name: ğŸ”„ï¸ CI

on:
  # https://blog.esciencecenter.nl/reduce-reuse-recycle-save-the-planet-one-github-action-at-a-time-4ab602255c3f
  push:
    paths:
      - .github/workflows/
      - src/
      - tests/
      - package.json
      - bun.lock
      - bunup.config.ts
      - tsconfig*.json
      - '!**/*.md'

  pull_request:
    paths:
      - .github/workflows/
      - src/
      - tests/
      - package.json
      - bun.lock
      - bunup.config.ts
      - tsconfig*.json
      - '!**/*.md'

  workflow_dispatch:

permissions: {}

jobs:
  lint:
    name: ğŸ” Lint
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip-ci]') }}
    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: ğŸ› ï¸ Setup Bun
        uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2

      - name: ğŸ“¦ Install dependencies
        run: bun install --frozen-lockfile --filter=.

      - name: ğŸ” Lint
        run: |
          bun run tsc
          bun run lint

  test:
    name: ğŸ§ª Tests
    if: ${{ !contains(github.event.head_commit.message, '[skip-ci]') }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: ğŸ› ï¸ Setup Bun
        uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2

      - name: ğŸ“¦ Install dependencies
        run: bun install --frozen-lockfile

      - name: ğŸ§ª Run tests
        run: bun run test
