name: Check PR Title

on:
  pull_request:
    types: [opened, edited]

permissions: {}

jobs:
  lint-pr-title:
    runs-on: ubuntu-latest

    if: ${{ (github.event.action == 'opened' || github.event.changes.title != null) && github.actor != 'dependabot[bot]' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          sparse-checkout-cone-mode: false
          sparse-checkout: .commitlintrc.yml

      - name: Install dependencies
        run: npm install --global @commitlint/config-conventional commitlint

      - name: Check PR title with commitlint
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          HELP_URL: https://github.com/bunup/bunup/blob/main/CONTRIBUTING.md#conventional-pr-titles
        run: echo "$PR_TITLE" | npx commitlint --help-url $HELP_URL
